exec "source ".g:CONFIG_PATH."/vim/lib/files.vim"
exec "source ".g:CONFIG_PATH."/vim/lib/hi.vim"
exec "source ".g:CONFIG_PATH."/vim/lib/numbers.vim"
exec "source ".g:CONFIG_PATH."/vim/lib/strings.vim"
exec "source ".g:CONFIG_PATH."/vim/lib/visual.vim"
