require('packages.vim-notify')
require('packages.lsp.plugins')
require('packages.treesitter')
require('packages.netrw')
require('packages.which-key')
vim.cmd('exec printf("so %s/lua/packages/mason.vim", g:CONFIG_PATH)')
